'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'
'     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
'     der Code wird erneut generiert. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Manage

    ''' <summary>
    ''' SuccessMessagePlaceHolder-Steuerelement
    ''' </summary>
    ''' <remarks>
    ''' Automatisch generiertes Feld.
    ''' Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    ''' </remarks>
    Protected WithEvents SuccessMessagePlaceHolder As Global.System.Web.UI.WebControls.PlaceHolder

    ''' <summary>
    ''' ChangePassword-Steuerelement
    ''' </summary>
    ''' <remarks>
    ''' Automatisch generiertes Feld.
    ''' Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    ''' </remarks>
    Protected WithEvents ChangePassword As Global.System.Web.UI.WebControls.HyperLink

    ''' <summary>
    ''' CreatePassword-Steuerelement
    ''' </summary>
    ''' <remarks>
    ''' Automatisch generiertes Feld.
    ''' Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    ''' </remarks>
    Protected WithEvents CreatePassword As Global.System.Web.UI.WebControls.HyperLink

    ''' <summary>
    ''' PhoneNumber-Steuerelement
    ''' </summary>
    ''' <remarks>
    ''' Automatisch generiertes Feld.
    ''' Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    ''' </remarks>
    Protected WithEvents PhoneNumber As Global.System.Web.UI.WebControls.Label
    
End Class
