'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'
'     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
'     der Code wird erneut generiert. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Register

    '''<summary>
    '''ErrorMessage-Steuerelement
    '''</summary>
    '''<remarks>
    '''Automatisch generiertes Feld.
    '''Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    '''</remarks>
    Protected WithEvents ErrorMessage As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Email control.
    '''</summary>
    '''<remarks>
    '''Automatisch generiertes Feld.
    '''Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    '''</remarks>
    Protected WithEvents Email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Password control.
    '''</summary>
    '''<remarks>
    '''Automatisch generiertes Feld.
    '''Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    '''</remarks>
    Protected WithEvents Password As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ConfirmPassword control.
    '''</summary>
    '''<remarks>
    '''Automatisch generiertes Feld.
    '''Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    '''</remarks>
    Protected WithEvents ConfirmPassword As Global.System.Web.UI.WebControls.TextBox
End Class
