'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'
'     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
'     der Code neu generiert wird. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TwoFactorAuthenticationSignIn

    '''<summary>
    '''sendcode-Steuerelement
    '''</summary>
    '''<remarks>
    '''Automatisch generiertes Feld.
    '''Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    '''</remarks>
    Protected WithEvents sendcode As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''Providers-Steuerelement
    '''</summary>
    '''<remarks>
    '''Automatisch generiertes Feld.
    '''Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    '''</remarks>
    Protected WithEvents Providers As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ProviderSubmit-Steuerelement
    '''</summary>
    '''<remarks>
    '''Automatisch generiertes Feld.
    '''Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    '''</remarks>
    Protected WithEvents ProviderSubmit As Global.System.Web.UI.WebControls.Button    

    '''<summary>
    '''verifycode-Steuerelement
    '''</summary>
    '''<remarks>
    '''Automatisch generiertes Feld.
    '''Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    '''</remarks>
    Protected WithEvents verifycode As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''SelectedProvider-Steuerelement
    '''</summary>
    '''<remarks>
    '''Automatisch generiertes Feld.
    '''Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    '''</remarks>
    Protected WithEvents SelectedProvider As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ErrorMessage-Steuerelement
    '''</summary>
    '''<remarks>
    '''Automatisch generiertes Feld.
    '''Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    '''</remarks>
    Protected WithEvents ErrorMessage As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''FailureText-Steuerelement
    '''</summary>
    '''<remarks>
    '''Automatisch generiertes Feld.
    '''Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    '''</remarks>
    Protected WithEvents FailureText As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Codesteuerelement
    '''</summary>
    '''<remarks>
    '''Automatisch generiertes Feld.
    '''Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    '''</remarks>
    Protected WithEvents Code As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RememberBrowser-Steuerelement
    '''</summary>
    '''<remarks>
    '''Automatisch generiertes Feld.
    '''Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    '''</remarks>
    Protected WithEvents RememberBrowser As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CodeSubmit-Steuerelement
    '''</summary>
    '''<remarks>
    '''Automatisch generiertes Feld.
    '''Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
    '''</remarks>
    Protected WithEvents CodeSubmit As Global.System.Web.UI.WebControls.Button
End Class
